deployment:
     imageURL: 888947293288.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
     imageVersion: 1.0.0 
hpa: 
   maxReplicas: 5
   utilization: 80      
configMap:
     MONGO_URL: mongodb://mongodb:27017/catalogue 
        